server:
  port: 8081

spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/201808?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  devtools:
     restart:
      enabled: true

  redis:
      host: localhost
      port: 6379
      password:

  jpa:
    hibernate:
     ddl-auto: update
     show-sql: true


    thymeleaf:
      cache: false
      enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: 1801a
  application:
      name:
      host: 15672
      port: 127.0.0.1
      username: guest
      password: guest
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp






